# Generated by Django 5.0.6 on 2024-06-12 09:09

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                default="IN",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
    ]
